services:
    nginx:
        image: nginx:alpine
        container_name: nginx_proxy
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - backend
        networks:
            - app-network
        restart: unless-stopped

    redis-cache:
        image: redis:7-alpine
        container_name: redis_cache
        restart: always
        volumes:
            - redis_data:/data
        networks:
            - app-network
        command: redis-server --bind 0.0.0.0

    backend:
        build: ./backend/
        container_name: backend
        volumes:
            - ./backend/:/app
        ports:
            - "8080:8080"
        depends_on:
            - redis-cache
        restart: unless-stopped
        command: python3 main.py
        networks:
            - app-network

networks:
    app-network:
volumes:
    redis_data:
